Renamed to 3X

diff --git a/assembler/3x-assemble b/assembler/3x-assemble
--- a/assembler/3x-assemble
+++ b/assembler/3x-assemble
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# exp-assemble -- assemble an experiment with given parameters
-# Usage: exp assemble OUTPUTDIR [NAME=VALUE]...
+# 3x-assemble -- assemble an experiment with given parameters
+# Usage: 3x assemble OUTPUTDIR [NAME=VALUE]...
 #
 # Author: Jaeho Shin <netj@cs.stanford.edu>
 # Created: 2012-11-01
@@ -8,35 +8,35 @@ set -eu
 
 [ $# -ge 1 ] || usage "$0" "At least OUTPUTDIR must be given"
 
-EXPWD=$1; shift
+_3X_WD=$1; shift
 
-EXPROOT=$(exp-findroot)
+_3X_ROOT=$(3x-findroot)
 
 # create the OUTPUTDIR with a working directory
-mkdir -p -- "$EXPWD"/workdir
+mkdir -p -- "$_3X_WD"/workdir
 
 # decide some important environment values
-EXPWD=$(readlink -f "$EXPWD")
-: ${EXPRUN:=${EXPWD#$EXPROOT/}}
-export EXPROOT EXPRUN EXPWD
-cd "$EXPROOT"
+_3X_WD=$(readlink -f "$_3X_WD")
+: ${_3X_RUN:=${_3X_WD#$_3X_ROOT/}}
+export _3X_ROOT _3X_RUN _3X_WD
+cd "$_3X_ROOT"
 
 # prepare the assemble script
 assembleScript=$(update-assembly-script)
 
 # assemble the inputs for experiment
-msg "Assembling $EXPRUN for $*"
-: >"$EXPWD"/assembly
+msg "Assembling $_3X_RUN for $*"
+: >"$_3X_WD"/assembly
 (
     # override some commands used in the assembly script
     error() {
         command error "$@"
-        touch "$EXPWD"/assembly.error
+        touch "$_3X_WD"/assembly.error
     }
     source() {
         # replace source with our function that avoids any evaluation in the definitions
         local f=$1
-        ! grep -qF "${f%/env}" "$EXPWD"/assembly || return 0
+        ! grep -qF "${f%/env}" "$_3X_WD"/assembly || return 0
         local decl= v= l=1
         while read -r decl; do
             decl=${decl%%*([ 	])#*}
@@ -56,37 +56,37 @@ msg "Assembling $EXPRUN for $*"
         msg +1 " recording environment as per ${envFiles[*]}: "$envVarNames
         {
             eval export -- $(no-comments "${envFiles[@]}" | sed 's/\([^=]*\)=\(.*\)/\1=${\1:-\2}/')
-            for v in $envVarNames; do echo "$v=${!v:-}"; done >"$EXPWD"/env
+            for v in $envVarNames; do echo "$v=${!v:-}"; done >"$_3X_WD"/env
             declare -r $envVarNames
         } >/dev/null
     fi
 
     # record input variables, so they can populate the environment
-    for param in "$@"; do echo "$param"; done >>"$EXPWD"/env
+    for param in "$@"; do echo "$param"; done >>"$_3X_WD"/env
     be-quiet +3 || set -x
     declare -r "$@"
 
     # repeat iterations with assembly script until no change
     assemble-iteration() {
-        wc -l <"$EXPWD"/assembly >"$EXPWD"/assembly.in-progress
+        wc -l <"$_3X_WD"/assembly >"$_3X_WD"/assembly.in-progress
         builtin source "$assembleScript"
-        [ $(wc -l <"$EXPWD"/assembly) -eq $(cat "$EXPWD"/assembly.in-progress) ]
+        [ $(wc -l <"$_3X_WD"/assembly) -eq $(cat "$_3X_WD"/assembly.in-progress) ]
     }
     while ! assemble-iteration; do :; done
-    rm -f "$EXPWD"/assembly.in-progress
+    rm -f "$_3X_WD"/assembly.in-progress
 )
 
 # check if assembly went ok
-[ ! -e "$EXPWD"/assembly.error ]
-if ! [ -x "$EXPWD"/workdir/run ]; then
-    error "Assembly failed for $EXPRUN: No executable \`run' exists"
+[ ! -e "$_3X_WD"/assembly.error ]
+if ! [ -x "$_3X_WD"/workdir/run ]; then
+    error "Assembly failed for $_3X_RUN: No executable \`run' exists"
 fi
 
 # record all input parameters again in a separate file
-for param in "$@"; do echo "$param"; done >"$EXPWD"/input
+for param in "$@"; do echo "$param"; done >"$_3X_WD"/input
 
 # make sure some files exist
-cp -af "$assembleScript" "$EXPWD"/assemble.sh
+cp -af "$assembleScript" "$_3X_WD"/assemble.sh
 for f in env args stdin; do
-    [ -e "$EXPWD/$f" ] || touch "$EXPWD/$f"
+    [ -e "$_3X_WD/$f" ] || touch "$_3X_WD/$f"
 done
diff --git a/assembler/import b/assembler/import
--- a/assembler/import
+++ b/assembler/import
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 # import -- import an input directory
-# Usage: cd $EXPROOT;  EXPWD=OUTPUTDIR import INPUTDIR...
+# Usage: cd $_3X_ROOT;  _3X_WD=OUTPUTDIR import INPUTDIR...
 #
 # Author: Jaeho Shin <netj@cs.stanford.edu>
 # Created: 2012-11-01
 set -eu
 
 [ $# -gt 0 ]        || usage "$0" "At least one INPUTDIR must be given"
-[ -n "${EXPWD:-}" ] || usage "$0" "EXPWD must be defined"
-EXPWDabbrev=${EXPWD#$PWD/}
+[ -n "${_3X_WD:-}" ] || usage "$0" "_3X_WD must be defined"
+_3X_WDabbrev=${_3X_WD#$PWD/}
 
 shopt -s extglob
 
 _recordCopiedFiles() {
     sed -E 's/^/  copying /;  s#([‘ ])run/.*/(workdir/|measures/|args)#\1\2#' |
-    tee -a "$EXPWD"/assembly
+    tee -a "$_3X_WD"/assembly
 }
 recordCopiedFiles() { _recordCopiedFiles >/dev/null; }
 be-quiet +1 || recordCopiedFiles() { _recordCopiedFiles >&2; }
@@ -45,15 +45,15 @@ copyFilesTo() {
 }
 
 for path in "$@"; do
-    if ! grep -qF "$path" "$EXPWD"/assembly; then
+    if ! grep -qF "$path" "$_3X_WD"/assembly; then
         msg " importing $path"
-        echo "$path" >>"$EXPWD"/assembly
+        echo "$path" >>"$_3X_WD"/assembly
         if [ -d "$path" ]; then
             # a directory containing files and nested patterns
             case $path in
                 @(input|program)/*)
                     # copy files
-                    copyFilesTo "$EXPWDabbrev"/workdir/ "$path" \
+                    copyFilesTo "$_3X_WDabbrev"/workdir/ "$path" \
                         -type f \( -name 'env' \
                                 -o -name 'args' -o -name '+args' -o -name 'args+' \
                                 -o -name 'unit' -o -name 'datatype' \
@@ -63,7 +63,7 @@ for path in "$@"; do
                     for f in env; do
                         if [ -r "$path"/$f ]; then
                             msg +1 "  appending $path/$f"
-                            no-comments "$path"/$f >>"$EXPWD"/$f
+                            no-comments "$path"/$f >>"$_3X_WD"/$f
                         fi
                     done
                     # command-line arguments
@@ -71,27 +71,27 @@ for path in "$@"; do
                         if [ -r "$a" ]; then
                             case ${a##*/} in
                                 args) # replace arguments
-                                    ! [ -e "$EXPWD"/args ] || error "$a cannot overwrite already existing args"
+                                    ! [ -e "$_3X_WD"/args ] || error "$a cannot overwrite already existing args"
                                     (
                                     set -o pipefail
-                                    cp -avn "$a" "$EXPWDabbrev"/args |
+                                    cp -avn "$a" "$_3X_WDabbrev"/args |
                                     recordCopiedFiles >&2
                                     )
                                     ;;
                                 args+) # append arguments
                                     msg +1 "  appending $a"
-                                    echo "  appending $a" >>"$EXPWD"/assembly
-                                    cat "$a" >>"$EXPWD"/args
+                                    echo "  appending $a" >>"$_3X_WD"/assembly
+                                    cat "$a" >>"$_3X_WD"/args
                                     ;;
                                 +args) # prepend arguments
                                     msg +1 "  prepending $a"
-                                    echo "  prepending $a" >>"$EXPWD"/assembly
+                                    echo "  prepending $a" >>"$_3X_WD"/assembly
                                     if [ -z "${tmp:-}" ]; then
-                                        tmp=$(mktemp /tmp/expkit-import.XXXXXX)
+                                        tmp=$(mktemp /tmp/3x-import.XXXXXX)
                                         trap "rm -f $tmp" EXIT
                                     fi
-                                    cat "$a" "$EXPWD"/args >$tmp
-                                    cat $tmp >"$EXPWD"/args
+                                    cat "$a" "$_3X_WD"/args >$tmp
+                                    cat $tmp >"$_3X_WD"/args
                                     ;;
                             esac
                         fi
@@ -102,7 +102,7 @@ for path in "$@"; do
                     m=${m#output/}
                     m=${m%%/*}
                     # copy files of output
-                    copyFilesTo "$EXPWDabbrev"/measures/"$m" "$path" \
+                    copyFilesTo "$_3X_WDabbrev"/measures/"$m" "$path" \
                         -type f \( -name 'unit' -o -name 'datatype' \
                                 \) \
                         #
diff --git a/batch/batch-loop b/batch/batch-loop
--- a/batch/batch-loop
+++ b/batch/batch-loop
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # batch-loop -- The loop that handles a batch
-# Usage: export EXPBATCH; cd $EXPROOT/$EXPBATCH; batch-loop
+# Usage: export _3X_BATCH; cd $_3X_ROOT/$_3X_BATCH; batch-loop
 #
 # Author: Jaeho Shin <netj@cs.stanford.edu>
 # Created: 2013-01-17
@@ -16,7 +16,7 @@ synchronized() {
 # prepare a remaining queue based on the plan
 if ! [ -e remaining -a -s count -a -d runs ]; then
     initialize() {
-        msg "Initializing $EXPBATCH"
+        msg "Initializing $_3X_BATCH"
         # append serial numbers to each line unless all lines already have one
         if grep -q -E -v '#[0-9]+$' <plan; then
             mv -f plan plan.orig
@@ -33,7 +33,7 @@ if ! [ -e remaining -a -s count -a -d runs ]; then
 fi
 if ! [ -s remaining ] && [[ $(find running.*/cmdln 2>/dev/null | wc -l) == 0 ]]; then
     rm -rf running.*/
-    msg "Nothing remaining for $EXPBATCH"
+    msg "Nothing remaining for $_3X_BATCH"
     exit 2
 fi
 
@@ -52,7 +52,7 @@ register-pid() {
 synchronized workers.lock register-pid
 
 # repeat until all "remaining" runs are done
-msg "Starting $EXPBATCH"
+msg "Starting $_3X_BATCH"
 count=$(cat count || wc -l <plan)
 abort=false
 trap "abort=true" INT QUIT TERM
@@ -81,11 +81,11 @@ while [ -s remaining ] && ! $abort; do
     line=$(cat $run/cmdln)
     serial=${line##*"#"}
     cmdln=${line%"#"*}
-    EXPRUN=$(new-run-id)
-    runRelPath="../../../${EXPRUN#run/}"
-    msg "Batch #$serial/$count of $EXPBATCH as $EXPRUN"
+    _3X_RUN=$(new-run-id)
+    runRelPath="../../../${_3X_RUN#run/}"
+    msg "Batch #$serial/$count of $_3X_BATCH as $_3X_RUN"
     ln -sfn "$runRelPath" $run/run
-    EXPRUN=$EXPRUN $cmdln || true
+    _3X_RUN=$_3X_RUN $cmdln || true
     ! $abort || break
     # after it ends, record the run in the "done" queue
     record() {
@@ -101,10 +101,10 @@ done
 lockproc $workerHandle release
 
 if $abort; then
-    error "Aborted $EXPBATCH" || true
+    error "Aborted $_3X_BATCH" || true
     msg "To resume, run:"
-    msg "  exp start $EXPBATCH"
+    msg "  3x start $_3X_BATCH"
     exit 2
 else
-    msg "Done $EXPBATCH"
+    msg "Done $_3X_BATCH"
 fi
diff --git a/planner/3x-plan b/planner/3x-plan
--- a/planner/3x-plan
+++ b/planner/3x-plan
@@ -1,17 +1,17 @@
 #!/usr/bin/env bash
-# exp-plan -- plan experiments with given variables
-# Usage: exp plan [PROGRAM] [NAME[=VALUE[,VALUE]...]]...
+# 3x-plan -- plan experiments with given variables
+# Usage: 3x plan [PROGRAM] [NAME[=VALUE[,VALUE]...]]...
 # 
-# Use `exp inputs -v` to list available input variables.
+# Use `3x inputs -v` to list available input variables.
 # 
 # 
-# Usage: exp plan results RESULTS_QUERY
-#        exp plan skip    RESULTS_QUERY
+# Usage: 3x plan results RESULTS_QUERY
+#        3x plan skip    RESULTS_QUERY
 # 
 # Another way to plan experiments is based on the results.  You can narrow
 # down the list of results and use the same set of inputs to plan more
 # experiments.  If you want to run inputs complementary to a set of
-# results, that is also possible with `exp plan skip`.  In this alternative
+# results, that is also possible with `3x plan skip`.  In this alternative
 # usage, you can plan more runs conditioning on the outputs so far.
 # 
 #
@@ -24,20 +24,20 @@ set -eu
     # show available variables
     echo
     echo "For full combination of inputs, run: "
-    echo "  exp plan "$(exp-inputs)
+    echo "  3x plan "$(3x-inputs)
     false
 }
 
-EXPROOT=$(exp-findroot)
-: ${EXPBATCH:=$(new-batch-id)}
-: ${EXPBATCH_STARTING:=false}
-export EXPROOT EXPBATCH
+_3X_ROOT=$(3x-findroot)
+: ${_3X_BATCH:=$(new-batch-id)}
+: ${_3X_BATCH_STARTING:=false}
+export _3X_ROOT _3X_BATCH
 
 # do a sanity check before we proceed
 update-assembly-script >/dev/null
 
 # create the batch directory
-tmp="$EXPROOT/$EXPBATCH"
+tmp="$_3X_ROOT/$_3X_BATCH"
 trap "rm -rf $tmp" EXIT
 mkdir -p -- "$tmp"
 
@@ -65,10 +65,10 @@ permute() {
 case $1 in
     with) # based on the given files
         shift
-        # adjust EXPROOT-relative paths
-        [ $# -eq 0 ] || [ -e "$1" ] || ! [ -e "$EXPROOT/$1" ] || {
+        # adjust _3X_ROOT-relative paths
+        [ $# -eq 0 ] || [ -e "$1" ] || ! [ -e "$_3X_ROOT/$1" ] || {
             path=$1; shift
-            set -- "$EXPROOT/$path" "$@"
+            set -- "$_3X_ROOT/$path" "$@"
         }
         [ -t 1 ] || EDITOR=true
         {
@@ -77,7 +77,7 @@ case $1 in
         } >"$tmp"/plan.editing
         # clean up any temporary file
         case $(readlink -f "$1") in
-            "$EXPROOT/.exp/plan.editing".*)
+            "$_3X_ROOT/.3x/plan.editing".*)
                 rm -f "$1"
                 ;;
         esac
@@ -88,10 +88,10 @@ case $1 in
 
         # record the query and fetch the results
         echo "$@" >"$tmp"/plan.$results.query
-        exp-results "$@" >"$tmp"/plan.$results
+        3x-results "$@" >"$tmp"/plan.$results
 
         # transform the results into a batch plan
-        cut -f$(( 1 + $(exp-outputs | wc -l) + 1 ))- <"$tmp"/plan.$results |
+        cut -f$(( 1 + $(3x-outputs | wc -l) + 1 ))- <"$tmp"/plan.$results |
         if $invertResults; then # TODO invert from the combination
             excl="$tmp"/plan.skipped
             sort | column -t >"$excl"
@@ -101,7 +101,7 @@ case $1 in
             comm -13 "$excl" -
         else awk '!seen[$0] {seen[$0]++;print}' # filter duplicate inputs
         fi |
-        sed 's/^/exp[[:space:]][[:space:]]*run[[:space:]][[:space:]]*/' | column -t >"$tmp"/plan.editing
+        sed 's/^/3x[[:space:]][[:space:]]*run[[:space:]][[:space:]]*/' | column -t >"$tmp"/plan.editing
         ;;
     *) # by editing combinations generated from given input values
         # normalize command-line arguments
@@ -110,35 +110,35 @@ case $1 in
 
         # permute the arguments and generate a batch plan
         msg "Permuting inputs for ${@%%=*}..."
-        permute "exp run" "$@" | column -t >"$tmp"/plan.editing
+        permute "3x run" "$@" | column -t >"$tmp"/plan.editing
         ;;
 esac
 
-cd "$EXPROOT/$EXPBATCH"
+cd "$_3X_ROOT/$_3X_BATCH"
 
 # let user do a finish edit of the generated plan
 if edit plan.editing plan.in-progress; then
     trap - EXIT
     sanitize() {
         local i=$1 o=$2
-        # check if every line starts with `exp run '
-        ! grep -Hn -E -v '^exp[[:space:]]+run[[:space:]]+|^[[:space:]]*$' "$i" ||
-            error "Syntax Error: All plan lines must start with \`exp run '" || return $?
+        # check if every line starts with `3x run '
+        ! grep -Hn -E -v '^3x[[:space:]]+run[[:space:]]+|^[[:space:]]*$' "$i" ||
+            error "Syntax Error: All plan lines must start with \`3x run '" || return $?
         # discard empty lines
         grep -E -v '^[[:space:]]*$' <"$i" >"$o"
-        # Skip checks of serials at the end of each line, since this is exp-starts' job
+        # Skip checks of serials at the end of each line, since this is 3x-starts' job
         #! grep -E -v '[[:space:]]+#[[:digit:]]+$' "$o" ||
-        #    error "$EXPBATCH/$i"': all plan lines must end with #SERIAL where SERIAL is a decimal number'
+        #    error "$_3X_BATCH/$i"': all plan lines must end with #SERIAL where SERIAL is a decimal number'
         # TODO check whether all input values are sane
     }
     sanitize plan.editing plan.editing.sanitized || {
-        cd "$EXPROOT"
-        # do not leave a bogus EXPBATCH, but clean it up
-        tmp=$(mktemp .exp/plan.editing.XXX)
-        cat "$EXPBATCH"/plan.editing >$tmp
-        rm -rf "$EXPBATCH"
+        cd "$_3X_ROOT"
+        # do not leave a bogus _3X_BATCH, but clean it up
+        tmp=$(mktemp .3x/plan.editing.XXX)
+        cat "$_3X_BATCH"/plan.editing >$tmp
+        rm -rf "$_3X_BATCH"
         msg "Edit the file and retry with the following command:"
-        msg "  exp plan with $tmp"
+        msg "  3x plan with $tmp"
         false
     }
     rm -f plan.editing
@@ -149,10 +149,10 @@ fi
 
 # and the batch creation is done
 msg +0 -n "Batch created at "
-if $EXPBATCH_STARTING; then
-    msg +0 "$EXPBATCH"
+if $_3X_BATCH_STARTING; then
+    msg +0 "$_3X_BATCH"
 else
-    echo "$EXPBATCH"
+    echo "$_3X_BATCH"
     msg "To start the batch, run:"
-    msg "  exp start $EXPBATCH"
+    msg "  3x start $_3X_BATCH"
 fi
