Migrating towards self-contained assembly script
(Rule of Generation)

diff --git a/assembler/generate-assembly-script b/assembler/generate-assembly-script
--- a/assembler/generate-assembly-script
+++ b/assembler/generate-assembly-script
@@ -87,4 +87,85 @@ codeForSourcing() {
 
 . "$TOOLSDIR"/sanity-checks.sh
 
+echo '#!/usr/bin/env bash
+# Usage: assemble.sh [INPUT_NAME=VALUE]... -- [ENV_NAME=VALUE]...
+set -eu
+be-quiet +3 || set -x
+
+# create the directory to be assembled
+_3X_ASSEMBLY_PRODUCT=$1; shift
+mkdir -p -- "$_3X_ASSEMBLY_PRODUCT"/workdir
+cp -f "$0" "$_3X_ASSEMBLY_PRODUCT"/assemble.sh
+cd "$_3X_ASSEMBLY_PRODUCT"
+unset _3X_ASSEMBLY_PRODUCT
+trap "rm -f assembly.in-progress" EXIT
+touch assembly.in-progress
+: >assembly
+
+# record and declare input parameters and environment variables
+: >env; : >input; endOfInput=false
+for param; do
+    case $param in --) endOfInput=true; continue ;; esac
+    declare -r "$param"
+    echo "$param" >>env
+    $endOfInput || echo "$param" >>input
+done
+unset param endOfInput
+
+
+# define how each iteration of assembly works
+assembly-iteration() {
+'
+
 codeForPatternDirs "$@"
+
+echo '
+}
+
+# define/override some commands used in the assembly script
+error() {
+    echo "$*" >>assembly.error
+    command error "$@"
+}
+
+source() {
+    # replace source with our function that avoids any evaluation in the definitions
+    local f=$1
+    ! grep -qxF "${f%/env}" assembly || return 0
+    local decl= v= l=1
+    while read -r decl; do
+        let l++
+        decl=${decl%%*([ 	])#*}
+        [ -n "$decl" ] || continue
+        v=${decl%%=*}
+        ! declare -p $v &>/dev/null || error "$f: line $l: $v: duplicate variable"
+        export "$decl"
+        declare -r $v
+        _3X_ASSEMBLY_CONTINUE=true
+    done <"$_3X_ROOT/$f"
+}
+import() {
+    local path
+    for path; do
+        ! grep -qxF "$path" assembly || continue
+        echo "$path" >>assembly
+        _3X_ASSEMBLY_CONTINUE=true
+        command import "$path"
+    done
+}
+
+# repeat iterations until no change
+_3X_ASSEMBLY_CONTINUE=true
+while $_3X_ASSEMBLY_CONTINUE; do
+    _3X_ASSEMBLY_CONTINUE=false
+    assembly-iteration
+done
+
+# make sure all essential files exist
+[ -x workdir/run ] || error "No executable \`run'\'' was assembled"
+for f in env args stdin; do
+    [ -e "$f" ] || touch "$f"
+done
+
+rm -f assembly.error
+'
