Assemble measurements and use them after runs

diff --git a/assembler/import b/assembler/import
--- a/assembler/import
+++ b/assembler/import
@@ -9,6 +9,8 @@ set -eu
 [ $# -gt 0 ]        || usage "$0" "At least one INPUTDIR must be given"
 [ -n "${EXPWD:-}" ] || usage "$0" "EXPWD must be defined"
 
+shopt -s extglob
+
 # TODO check if cp is GNU coreutil's
 cpopts=
 be-quiet +1 || cpopts+=--verbose
@@ -19,46 +21,62 @@ for path in "$@"; do
         echo "$path" >>"$EXPWD"/exp.assembly
         if [ -d "$path" ]; then
             # a directory containing files and nested patterns
-            # copy files
-            find "$path" -mindepth 1 -maxdepth 1 ! \( -name 'env' \
-                -o -type d -name '*=*' -prune \
-                -o -name 'args' -o -name '+args' -o -name 'args+' \
-                \) -print 2>/dev/null |
-            xargs cp $cpopts --archive --link --target-directory="$EXPWD"/ |
-            # TODO check and emit error if any files get overwritten
-            sed 's/^/  linking /'
-            # environment variables
-            for f in env; do
-                if [ -r "$path"/$f ]; then
-                    msg +1 "  appending $path/$f"
-                    no-comments "$path"/$f >>"$EXPWD"/$f
-                fi
-            done
-            # command-line arguments
-            for a in "$path"/{args,+args,args+}; do
-                if [ -r "$a" ]; then
-                    case ${a##*/} in
-                        args) # replace arguments
-                            ! [ -e "$EXPWD"/args ] || error "$a cannot overwrite already existing args"
-                            cp $cpopts --no-clobber "$a" "$EXPWD"/args |
-                            sed 's/^/  linking /'
-                            ;;
-                        args+) # append arguments
-                            msg +1 "  appending $a"
-                            cat "$a" >>"$EXPWD"/args
-                            ;;
-                        +args) # prepend arguments
-                            msg +1 "  prepending $a"
-                            if [ -z "${tmp:-}" ]; then
-                                tmp=$(mktemp /tmp/expkit-import.XXXXXX)
-                                trap "rm -f $tmp" EXIT
-                            fi
-                            cat "$a" "$EXPWD"/args >$tmp
-                            cat $tmp >"$EXPWD"/args
-                            ;;
-                    esac
-                fi
-            done
+            case $path in
+                @(condition|program)/*)
+                    # copy files
+                    find "$path" -mindepth 1 -maxdepth 1 ! \( -name 'env' \
+                        -o -type d -name '*=*' -prune \
+                        -o -name 'args' -o -name '+args' -o -name 'args+' \
+                        \) -print 2>/dev/null |
+                    xargs cp $cpopts --archive --link --target-directory="$EXPWD"/ |
+                    # TODO check and emit error if any files get overwritten
+                    sed 's/^/  linking /'
+                    # environment variables
+                    for f in env; do
+                        if [ -r "$path"/$f ]; then
+                            msg +1 "  appending $path/$f"
+                            no-comments "$path"/$f >>"$EXPWD"/$f
+                        fi
+                    done
+                    # command-line arguments
+                    for a in "$path"/{args,+args,args+}; do
+                        if [ -r "$a" ]; then
+                            case ${a##*/} in
+                                args) # replace arguments
+                                    ! [ -e "$EXPWD"/args ] || error "$a cannot overwrite already existing args"
+                                    cp $cpopts --no-clobber "$a" "$EXPWD"/args |
+                                    sed 's/^/  linking /'
+                                    ;;
+                                args+) # append arguments
+                                    msg +1 "  appending $a"
+                                    cat "$a" >>"$EXPWD"/args
+                                    ;;
+                                +args) # prepend arguments
+                                    msg +1 "  prepending $a"
+                                    if [ -z "${tmp:-}" ]; then
+                                        tmp=$(mktemp /tmp/expkit-import.XXXXXX)
+                                        trap "rm -f $tmp" EXIT
+                                    fi
+                                    cat "$a" "$EXPWD"/args >$tmp
+                                    cat $tmp >"$EXPWD"/args
+                                    ;;
+                            esac
+                        fi
+                    done
+                    ;;
+                measure/*)
+                    m=$path
+                    m=${m#measure/}
+                    m=${m%%/*}
+                    md="$EXPWD"/exp.measure/"$m"
+                    # copy files for measurement
+                    mkdir -p "$md"
+                    find "$path" -mindepth 1 -maxdepth 1 -print 2>/dev/null |
+                    xargs cp $cpopts --archive --link \
+                        --target-directory="$md"/ |
+                    sed 's/^/  linking /'
+                    ;;
+            esac
         else
             # .env files
             if [ -r "$path" ]; then
