Made resuming possible for base.async runners
By reusing an enhanced base.multi runner's dequeue.  Interrupting
`queue-start` can mark all runs as ABORTED if `start-all` fails, and
a later `queue-start` invocation can reschedule them.  Actual base.async
runners can touch the `scheduled` file as soon as they schedule some
runs, so it won't be rescheduled and can be synced/stopped later.

It seems a new state (SCHEDULED?) for runs is necessary to indicate the
run has been scheduled but not yet RUNNING.  `refresh-all` can quickly
poll how many are actually RUNNING and still waiting at SCHEDULED.
Then, `refresh-all` would probably also need to mark runs that have been
found finished but whose records were not fetched/synchronized to the
repository yet (as FINISHED?).  Ideally, it should be possible to change
the order of SCHEDULED runs, but not the ones in the other two: RUNNING
or FINISHED.

diff --git a/runner/base/multi/dequeue b/runner/base/multi/dequeue
--- a/runner/base/multi/dequeue
+++ b/runner/base/multi/dequeue
@@ -35,13 +35,14 @@ for-picked-runs list-only runId >"$_3X_WORKER_DIR"/runIds
 # mark as ABORTED upon queue-stop or interrupt
 exit-after-marking-as-aborted() {
     c=$?
+    [[ $# -gt 0 ]] || set -- "$(cat "$_3X_WORKER_DIR"/target.aborted.cause)"
     runner-error "${*:-Execution aborted due to error}" || true
     # mark all unfinished runs as ABORTED
     drop-finished-runs
     xargs <"$_3X_WORKER_DIR"/runSerials         queue mark-as ABORTED
     # create target.aborted in each run dir
     {
-        echo "$*"
+        [[ $# -eq 0 ]] || echo "$*"
         cat "$_3X_WORKER_DIR"/error 2>/dev/null || true
     } >"$_3X_WORKER_DIR"/target.aborted
     cd "$_3X_ROOT"
@@ -52,12 +53,13 @@ exit-after-marking-as-aborted() {
     #XXX xargs <"$_3X_WORKER_DIR"/runIds         chmod -w
     exit $c
 }
+rm -f "$_3X_WORKER_DIR"/target.aborted.cause
 for sig in INT QUIT TERM; do
     case $sig in
         TERM) msg="Execution stopped" ;;
         *) msg="Execution interrupted" ;;
     esac
-    trap 'exit-after-marking-as-aborted "'"$msg"'"' $sig
+    trap 'echo "'"$msg"'" >>"$_3X_WORKER_DIR"/target.aborted.cause' $sig
 done
 
 
@@ -68,4 +70,4 @@ runner-msg "Executing #$firstSerial through #$lastSerial ($count runs)"
 
 _3X_LOGERROR="$_3X_WORKER_DIR"/error \
 run-all "$_3X_WORKER_DIR" ||
-    || exit-after-marking-as-aborted
+    exit-after-marking-as-aborted
diff --git a/runner/ssh-cluster/start-all b/runner/ssh-cluster/start-all
--- a/runner/ssh-cluster/start-all
+++ b/runner/ssh-cluster/start-all
@@ -22,7 +22,7 @@ numRuns=$(wc -l <runSerials)
 
 # filter out unresponsive remotes first
 runner-msg "finding availability of ${#remotes[@]} remote hosts"
-touch remotes.alive
+: >remotes.alive
 requiresSSHCommand
 pollRemote() {
     local remote=$1
@@ -106,8 +106,10 @@ scheduleRuns() {
     # record which remote host is running which runs
     echo $remote >$split.remote
     echo $remote >>remotes
-    touch "$_3X_QUEUE_DIR"/$ACTIVE_FLAG
+    touch scheduled "$_3X_QUEUE_DIR"/$ACTIVE_FLAG
     ssh-3x-remote $remote start <$split
 }
-eachInParallel scheduleRuns "${remotes[@]}"
-waitAll
+# once runs are scheduled at at least one remote, we should not fail
+trap 'exit 0' INT QUIT TERM
+eachInParallel scheduleRuns "${remotes[@]}" || true
+waitAll || true
