Changed output extractors' CWD to workdir/
Otherwise, it is difficult to write a simple script, e.g., in Python
that produces additional files.

diff --git a/results/extract-output b/results/extract-output
--- a/results/extract-output
+++ b/results/extract-output
@@ -24,22 +24,25 @@ cd "$_3X_ROOT/$_3X_RUN"
 
 msg "$_3X_RUN: extracting output"
 rm -f outputs.failed
-for ox in outputs/*/$_3X_API_EXTRACTOR; do
+{
+cd ./workdir
+for ox in ../outputs/*/$_3X_API_EXTRACTOR; do
     [[ -z "$_3X_EXTRACT_ONLY" ]] ||
-        [[ "$ox" == outputs/$_3X_EXTRACT_ONLY/$_3X_API_EXTRACTOR ]] || continue
+        [[ "$ox" == ../outputs/$_3X_EXTRACT_ONLY/$_3X_API_EXTRACTOR ]] || continue
     if [ -x "$ox" ]; then
         od=$(dirname "$ox")
         o=$(basename "$od") oerr="$od/stderr"
         v=$(
             # running extractor under the same env
-            export $(cat ./env) _3X_MEASURE=${ox%/$_3X_API_EXTRACTOR}
+            # TODO start from a clean env?
+            export $(cat ../env) _3X_OUTPUT=${ox%/$_3X_API_EXTRACTOR}
             PATH="$PATH:$TOOLSDIR"
             if "$ox" 2>"$oerr"; then
                 # only keep non-empty stderr logs
                 [ -s "$oerr" ] || rm -f "$oerr"
             else # keep going on any failed extractor
                 # but keep track of their names and exit status
-                echo "$o (exit status=$?)" >>outputs.failed
+                echo "$o (exit status=$?)" >>../outputs.failed
             fi
         )
         case $v in # try not to wrap quotes around empty value
@@ -49,7 +52,9 @@ for ox in outputs/*/$_3X_API_EXTRACTOR; do
         # finally record a name/value-pair line for each output
         echo "$o=$v"
     fi
-done >>output
+done
+cd ..
+} >>output
 
 # see if all output extractors ended successfully
 ! [ -s outputs.failed ] ||
